<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Catalog label translations (TR source → EN / IT display)
    | Keys must match stored admin/option values (case-insensitive match at runtime).
    |--------------------------------------------------------------------------
    */
    'labels' => [
        // Gender / audience
        'Erkek' => ['en' => 'Men', 'it' => 'Uomo'],
        'Kadın' => ['en' => 'Women', 'it' => 'Donna'],
        'Bayan' => ['en' => 'Women', 'it' => 'Donna'],
        'Unisex' => ['en' => 'Unisex', 'it' => 'Unisex'],
        'Çocuk' => ['en' => 'Kids', 'it' => 'Bambini'],
        'Çoçuk' => ['en' => 'Kids', 'it' => 'Bambini'],
        'Erkek/Unisex' => ['en' => 'Men/Unisex', 'it' => 'Uomo/Unisex'],
        'Erkek/Bayan' => ['en' => 'Men/Women', 'it' => 'Uomo/Donna'],

        // Size tables
        'Erkek/Unisex Beden Tablosu' => ['en' => 'Men/Unisex size chart', 'it' => 'Tabella taglie uomo/unisex'],
        'Erkek Beden Tablosu' => ['en' => 'Men size chart', 'it' => 'Tabella taglie uomo'],
        'Kadın Beden Tablosu' => ['en' => 'Women size chart', 'it' => 'Tabella taglie donna'],
        'Kadın Beden Seçiniz' => ['en' => 'Choose women sizes', 'it' => 'Scegli taglie donna'],
        'BEDEN TABLOSU (ERKEK)' => ['en' => 'SIZE CHART (MEN)', 'it' => 'TABELLA TAGLIE (UOMO)'],
        'BEDEN TABLOSU (ERKEK/UNISEX)' => ['en' => 'SIZE CHART (MEN/UNISEX)', 'it' => 'TABELLA TAGLIE (UOMO/UNISEX)'],
        'BEDEN - ÇOCUK' => ['en' => 'KIDS SIZES', 'it' => 'TAGLIE BAMBINI'],

        // Common variation names
        'Cinsiyet' => ['en' => 'Gender', 'it' => 'Genere'],
        'Cinsiyet Seçiniz' => ['en' => 'Select gender', 'it' => 'Seleziona genere'],
        'Renk' => ['en' => 'Color', 'it' => 'Colore'],
        'Beden' => ['en' => 'Size', 'it' => 'Taglia'],
        'Kumaş' => ['en' => 'Fabric', 'it' => 'Tessuto'],
        'Kumaş Türü' => ['en' => 'Fabric type', 'it' => 'Tipo di tessuto'],
        'Kalıp' => ['en' => 'Fit / mold', 'it' => 'Modello'],
        'Kalıp Model' => ['en' => 'Fit model', 'it' => 'Modello vestibilità'],
        'Kalıp / Model' => ['en' => 'Fit / Model', 'it' => 'Modello'],
        'Etiket' => ['en' => 'Label', 'it' => 'Etichetta'],
        'Etiket Tipi' => ['en' => 'Label type', 'it' => 'Tipo etichetta'],
        'Paketleme' => ['en' => 'Packaging', 'it' => 'Imballaggio'],
        'Paketleme Tipi' => ['en' => 'Packaging type', 'it' => 'Tipo di imballaggio'],
        'Teslimat' => ['en' => 'Delivery', 'it' => 'Consegna'],
        'Teslim Şekli' => ['en' => 'Delivery method', 'it' => 'Metodo di consegna'],
        'Sipariş Adeti' => ['en' => 'Order quantity', 'it' => 'Quantità ordine'],
        'Beden Seçiniz' => ['en' => 'Select size', 'it' => 'Seleziona taglia'],
        'Model Seçiniz' => ['en' => 'Select model', 'it' => 'Seleziona modello'],
        'Kalıp Seçiniz' => ['en' => 'Select fit', 'it' => 'Seleziona vestibilità'],
        'Kumaş Seçiniz' => ['en' => 'Select fabric', 'it' => 'Seleziona tessuto'],
        'Teknik Detaylar ve Aksesuarlar' => ['en' => 'Technical details and accessories', 'it' => 'Dettagli tecnici e accessori'],

        // Print technique labels often stored in DB
        'Emprime' => ['en' => 'Screen print', 'it' => 'Serigrafia'],
        'Emprime Baskı' => ['en' => 'Screen print', 'it' => 'Serigrafia'],
        'Nakış' => ['en' => 'Embroidery', 'it' => 'Ricamo'],
        'DTF' => ['en' => 'DTF print', 'it' => 'Stampa DTF'],
        'DTF Baskı' => ['en' => 'DTF print', 'it' => 'Stampa DTF'],
        'Direkt Dijital' => ['en' => 'Direct digital print', 'it' => 'Stampa digitale diretta'],
        'Direkt Dijital Baskı' => ['en' => 'Direct digital print', 'it' => 'Stampa digitale diretta'],
        'Dijital Baskı' => ['en' => 'Digital print', 'it' => 'Stampa digitale'],
        'Serigrafi' => ['en' => 'Screen print', 'it' => 'Serigrafia'],

        // Print positions (common)
        'Sağ Ön Göğüs' => ['en' => 'Right front chest', 'it' => 'Petto anteriore destro'],
        'Sol Ön Göğüs' => ['en' => 'Left front chest', 'it' => 'Petto anteriore sinistro'],
        'Sağ Göğüs' => ['en' => 'Right chest', 'it' => 'Petto destro'],
        'Sol Göğüs' => ['en' => 'Left chest', 'it' => 'Petto sinistro'],
        'Ön Göğüs' => ['en' => 'Front chest', 'it' => 'Petto anteriore'],
        'Orta Göğüs' => ['en' => 'Center chest', 'it' => 'Petto centrale'],
        'Sırt' => ['en' => 'Back', 'it' => 'Schiena'],
        'Sırt Ortası' => ['en' => 'Center back', 'it' => 'Schiena centrale'],
        'Sağ Kol' => ['en' => 'Right sleeve', 'it' => 'Manica destra'],
        'Sol Kol' => ['en' => 'Left sleeve', 'it' => 'Manica sinistra'],
        'Ense' => ['en' => 'Nape / neck back', 'it' => 'Nuca'],
        'Boyun' => ['en' => 'Neck', 'it' => 'Collo'],

        // Generic UI catalog words
        'Evet' => ['en' => 'Yes', 'it' => 'Sì'],
        'Hayır' => ['en' => 'No', 'it' => 'No'],
        'Yok' => ['en' => 'None', 'it' => 'Nessuno'],
        'Standart' => ['en' => 'Standard', 'it' => 'Standard'],
        'Özel' => ['en' => 'Custom', 'it' => 'Personalizzato'],
        'Beyaz' => ['en' => 'White', 'it' => 'Bianco'],
        'Siyah' => ['en' => 'Black', 'it' => 'Nero'],
        'Lacivert' => ['en' => 'Navy', 'it' => 'Blu navy'],
        'Gri' => ['en' => 'Grey', 'it' => 'Grigio'],
        'Kırmızı' => ['en' => 'Red', 'it' => 'Rosso'],
        'Mavi' => ['en' => 'Blue', 'it' => 'Blu'],
        'Yeşil' => ['en' => 'Green', 'it' => 'Verde'],
        'Sarı' => ['en' => 'Yellow', 'it' => 'Giallo'],
        'Pembe' => ['en' => 'Pink', 'it' => 'Rosa'],
        'Mor' => ['en' => 'Purple', 'it' => 'Viola'],
        'Bordo' => ['en' => 'Burgundy', 'it' => 'Bordeaux'],
        'Bej' => ['en' => 'Beige', 'it' => 'Beige'],
        'Kahverengi' => ['en' => 'Brown', 'it' => 'Marrone'],
        'Turuncu' => ['en' => 'Orange', 'it' => 'Arancione'],
        'Antrasit' => ['en' => 'Anthracite', 'it' => 'Antracite'],
        'Camel' => ['en' => 'Camel', 'it' => 'Cammello'],
        'Eflatun' => ['en' => 'Lilac', 'it' => 'Lilla'],
        'Navy' => ['en' => 'Navy', 'it' => 'Blu navy'],
        'Kırık Beyaz' => ['en' => 'Off-white', 'it' => 'Bianco sporco'],
        'Açık Gri' => ['en' => 'Light grey', 'it' => 'Grigio chiaro'],
        'Krema' => ['en' => 'Cream', 'it' => 'Panna'],
        'Vanilya' => ['en' => 'Vanilla', 'it' => 'Vaniglia'],
        'Kum' => ['en' => 'Sand', 'it' => 'Sabbia'],
        'Açık Kahve' => ['en' => 'Light brown', 'it' => 'Marrone chiaro'],
        'Bronz' => ['en' => 'Bronze', 'it' => 'Bronzo'],
        'Bebek Pembesi' => ['en' => 'Baby pink', 'it' => 'Rosa baby'],
        'Tarçın' => ['en' => 'Cinnamon', 'it' => 'Cannella'],
        'Koyu Kahve' => ['en' => 'Dark brown', 'it' => 'Marrone scuro'],
        'Espresso' => ['en' => 'Espresso', 'it' => 'Espresso'],
        'Zeytin Yeşili' => ['en' => 'Olive green', 'it' => 'Verde oliva'],
        'Açık Yeşil' => ['en' => 'Light green', 'it' => 'Verde chiaro'],
        'Orman Yeşili' => ['en' => 'Forest green', 'it' => 'Verde bosco'],
        'Nane Yeşili' => ['en' => 'Mint green', 'it' => 'Verde menta'],
        'Teal' => ['en' => 'Teal', 'it' => 'Verde acqua'],
        'Turkuaz' => ['en' => 'Turquoise', 'it' => 'Turchese'],
        'Koyu Yeşil' => ['en' => 'Dark green', 'it' => 'Verde scuro'],
        'Açık Mavi' => ['en' => 'Light blue', 'it' => 'Azzurro'],
        'Gök Mavisi' => ['en' => 'Sky blue', 'it' => 'Blu cielo'],
        'Koyu Mavi' => ['en' => 'Dark blue', 'it' => 'Blu scuro'],
        'Kraliyet Mavisi' => ['en' => 'Royal blue', 'it' => 'Blu royal'],
        'Gece Mavisi' => ['en' => 'Night blue', 'it' => 'Blu notte'],
        'Petrol Mavisi' => ['en' => 'Petroleum blue', 'it' => 'Blu petrolio'],
        'Gece Laciverti' => ['en' => 'Midnight navy', 'it' => 'Blu navy scuro'],
        'Çelik Mavisi' => ['en' => 'Steel blue', 'it' => 'Blu acciaio'],
        'Doğal' => ['en' => 'Natural', 'it' => 'Naturale'],
        'Pastel Pembe' => ['en' => 'Pastel pink', 'it' => 'Rosa pastello'],
        'Açık Pembe' => ['en' => 'Light pink', 'it' => 'Rosa chiaro'],
        'Orta Gri' => ['en' => 'Medium grey', 'it' => 'Grigio medio'],
        'Canlı Pembe' => ['en' => 'Hot pink', 'it' => 'Rosa vivace'],
        'Koyu Gri' => ['en' => 'Dark grey', 'it' => 'Grigio scuro'],
        'Fuşya' => ['en' => 'Fuchsia', 'it' => 'Fucsia'],
        'Lavanta' => ['en' => 'Lavender', 'it' => 'Lavanda'],
        'İndigo' => ['en' => 'Indigo', 'it' => 'Indaco'],
        'Parlak Kırmızı' => ['en' => 'Bright red', 'it' => 'Rosso brillante'],
        'Altın Sarı' => ['en' => 'Golden yellow', 'it' => 'Giallo oro'],
        'Altın' => ['en' => 'Gold', 'it' => 'Oro'],
        'Sarı Altın' => ['en' => 'Gold yellow', 'it' => 'Giallo dorato'],
        'Haki' => ['en' => 'Khaki', 'it' => 'Cachi'],
        'Zeytin' => ['en' => 'Olive', 'it' => 'Oliva'],
        'Koyu Zeytin' => ['en' => 'Dark olive', 'it' => 'Oliva scuro'],
        'Zümrüt Yeşili' => ['en' => 'Emerald green', 'it' => 'Verde smeraldo'],
        'Gümüş Gri' => ['en' => 'Silver grey', 'it' => 'Grigio argento'],
        'Kül Rengi' => ['en' => 'Ash grey', 'it' => 'Grigio cenere'],
        'Kömür Gri' => ['en' => 'Charcoal grey', 'it' => 'Grigio carbone'],
        'Deniz Laciverti' => ['en' => 'Navy', 'it' => 'Blu navy'],

        // Categories / product groups
        'Üst Giyim' => ['en' => 'Tops', 'it' => 'Abbigliamento superiore'],
        'Alt Giyim' => ['en' => 'Bottoms', 'it' => 'Abbigliamento inferiore'],
        'Dış Giyim' => ['en' => 'Outerwear', 'it' => 'Outerwear'],
        'Kadın Giyim' => ['en' => 'Women’s clothing', 'it' => 'Abbigliamento donna'],
        'Aksesuar' => ['en' => 'Accessories', 'it' => 'Accessori'],
        'Tişört' => ['en' => 'T-shirt', 'it' => 'T-shirt'],
        'Gömlek' => ['en' => 'Shirt', 'it' => 'Camicia'],
        'Kazak' => ['en' => 'Sweater', 'it' => 'Maglione'],
        'Ceket' => ['en' => 'Jacket', 'it' => 'Giacca'],
        'Bluz' => ['en' => 'Blouse', 'it' => 'Camicetta'],
        'Triko Yelek' => ['en' => 'Knit vest', 'it' => 'Gilet in maglia'],
        'Pantolon' => ['en' => 'Trousers', 'it' => 'Pantaloni'],
        'Şort' => ['en' => 'Shorts', 'it' => 'Shorts'],
        'Etek' => ['en' => 'Skirt', 'it' => 'Gonna'],
        'Kaban' => ['en' => 'Coat', 'it' => 'Cappotto'],
        'Mont' => ['en' => 'Parka', 'it' => 'Giubbotto'],
        'Elbise' => ['en' => 'Dress', 'it' => 'Vestito'],
        'Atkı' => ['en' => 'Scarf', 'it' => 'Sciarpa'],
        'Kravat' => ['en' => 'Tie', 'it' => 'Cravatta'],
        'Ev Tekstili' => ['en' => 'Home textiles', 'it' => 'Tessile per la casa'],
        'Promosyon' => ['en' => 'Promotional', 'it' => 'Promozionale'],
        'Bags' => ['en' => 'Bags', 'it' => 'Borse'],
        'Towels' => ['en' => 'Towels', 'it' => 'Asciugamani'],
        'Hats' => ['en' => 'Hats', 'it' => 'Cappelli'],
        'Aprons' => ['en' => 'Aprons', 'it' => 'Grembiuli'],

        // English catalog titles (keep EN, fill IT)
        'Hoodie' => ['en' => 'Hoodie', 'it' => 'Felpa con cappuccio'],
        'Apron' => ['en' => 'Apron', 'it' => 'Grembiule'],
        'Backpack' => ['en' => 'Backpack', 'it' => 'Zaino'],
        'Bandana' => ['en' => 'Bandana', 'it' => 'Bandana'],
        'Baseball Hat' => ['en' => 'Baseball hat', 'it' => 'Cappello baseball'],
        'Beach Towel' => ['en' => 'Beach towel', 'it' => 'Telo mare'],
        'Boiler Suit' => ['en' => 'Boiler suit', 'it' => 'Tuta da lavoro'],
        'Bucket Hat' => ['en' => 'Bucket hat', 'it' => 'Cappello a secchiello'],
        'Fleece Scarf' => ['en' => 'Fleece scarf', 'it' => 'Sciarpa in pile'],
        'Lab Coat' => ['en' => 'Lab coat', 'it' => 'Camice da laboratorio'],
        'Napkins' => ['en' => 'Napkins', 'it' => 'Tovaglioli'],
        'Pillow' => ['en' => 'Pillow', 'it' => 'Cuscino'],
        'Puffer Vest' => ['en' => 'Puffer vest', 'it' => 'Gilet imbottito'],
        'Runner' => ['en' => 'Runner', 'it' => 'Runner'],
        'Shirt' => ['en' => 'Shirt', 'it' => 'Camicia'],
        'Socks' => ['en' => 'Socks', 'it' => 'Calzini'],
        'Sweater' => ['en' => 'Sweater', 'it' => 'Maglione'],
        'Sweatshirt' => ['en' => 'Sweatshirt', 'it' => 'Felpa'],
        'Tablecloth' => ['en' => 'Tablecloth', 'it' => 'Tovaglia'],
        'Team Jersey' => ['en' => 'Team jersey', 'it' => 'Maglia da squadra'],
        'Tote Bag' => ['en' => 'Tote bag', 'it' => 'Borsa shopper'],
        'Trucker Hat' => ['en' => 'Trucker hat', 'it' => 'Cappello trucker'],
        'Winter Hats' => ['en' => 'Winter hats', 'it' => 'Cappelli invernali'],
        'Workwear Bib' => ['en' => 'Workwear bib', 'it' => 'Salopette da lavoro'],
        'Workwear Jacket' => ['en' => 'Workwear jacket', 'it' => 'Giacca da lavoro'],

        // Packaging / delivery / extras
        'OPP Şeffaf' => ['en' => 'OPP transparent', 'it' => 'OPP trasparente'],
        'Kara yolu' => ['en' => 'Road freight', 'it' => 'Via terra'],
        'Deniz yolu' => ['en' => 'Sea freight', 'it' => 'Via mare'],
        'Havayolu' => ['en' => 'Air freight', 'it' => 'Via aerea'],
        'Karayolu' => ['en' => 'Road freight', 'it' => 'Via terra'],
        'Denizyolu' => ['en' => 'Sea freight', 'it' => 'Via mare'],
        'Amabalaj Tercihi' => ['en' => 'Packaging preference', 'it' => 'Preferenza imballaggio'],
        'Ambalaj Tercihi' => ['en' => 'Packaging preference', 'it' => 'Preferenza imballaggio'],
        'Ense Biyesi' => ['en' => 'Nape bias tape', 'it' => 'Bies nuca'],
        'Ense Ay Parçası' => ['en' => 'Nape hanger loop', 'it' => 'Asola nuca'],
        'Renkli Ense Biyesi' => ['en' => 'Colored nape tape', 'it' => 'Bies nuca colorato'],
        'Kilitli Torba' => ['en' => 'Zip bag', 'it' => 'Busta zip'],
        'Dikim Yeri' => ['en' => 'Sewing location', 'it' => 'Punto di cucitura'],
        'Mat' => ['en' => 'Matte', 'it' => 'Opaco'],
        'SLIM' => ['en' => 'Slim', 'it' => 'Slim'],
        'FIT' => ['en' => 'Fit', 'it' => 'Fit'],
        'REGULAR' => ['en' => 'Regular', 'it' => 'Regular'],
        'OVERSIZE' => ['en' => 'Oversize', 'it' => 'Oversize'],
        'Regular' => ['en' => 'Regular', 'it' => 'Regular'],
        'Oversize' => ['en' => 'Oversize', 'it' => 'Oversize'],
        'SLİM' => ['en' => 'Slim', 'it' => 'Slim'],
        'deneme' => ['en' => 'Trial', 'it' => 'Prova'],

        // Dump-specific variation titles (matching keys stay as stored; display only)
        'Choose a mold' => ['tr' => 'Kalıp seçiniz', 'en' => 'Select fit', 'it' => 'Seleziona vestibilità'],
        'Select a Model' => ['tr' => 'Model seçiniz', 'en' => 'Select model', 'it' => 'Seleziona modello'],
        'Select a model.' => ['tr' => 'Model seçiniz', 'en' => 'Select model', 'it' => 'Seleziona modello'],
        'Select gender' => ['tr' => 'Cinsiyet seçiniz', 'en' => 'Select gender', 'it' => 'Seleziona genere'],
        'Choose a color.' => ['tr' => 'Renk seçiniz', 'en' => 'Select color', 'it' => 'Seleziona colore'],
        'Renk Seçiniz' => ['en' => 'Select color', 'it' => 'Seleziona colore'],
        'Renk seçiniz' => ['en' => 'Select color', 'it' => 'Seleziona colore'],
        'Choose your fabric.' => ['tr' => 'Kumaş seçiniz', 'en' => 'Select fabric', 'it' => 'Seleziona tessuto'],
        'Technical Details and Accessories' => ['tr' => 'Teknik detaylar ve aksesuarlar', 'en' => 'Technical details and accessories', 'it' => 'Dettagli tecnici e accessori'],
        'Teknik Detaylar' => ['en' => 'Technical details', 'it' => 'Dettagli tecnici'],
        'Teknik detaylar' => ['en' => 'Technical details', 'it' => 'Dettagli tecnici'],
        'Order Quantity' => ['tr' => 'Sipariş adedi', 'en' => 'Order quantity', 'it' => 'Quantità ordine'],
        'Specify the label type.' => ['tr' => 'Etiket türü belirle', 'en' => 'Select label type', 'it' => 'Seleziona tipo etichetta'],
        'Etiket Türü belirle' => ['en' => 'Select label type', 'it' => 'Seleziona tipo etichetta'],
        'Etiket Türü Belirle' => ['en' => 'Select label type', 'it' => 'Seleziona tipo etichetta'],
        'Etiket türü belirle' => ['en' => 'Select label type', 'it' => 'Seleziona tipo etichetta'],
        'Etiket seçimiz' => ['en' => 'Select label', 'it' => 'Seleziona etichetta'],
        'Etiket seçiniz' => ['en' => 'Select label', 'it' => 'Seleziona etichetta'],
        'Etiket Seçiniz' => ['en' => 'Select label', 'it' => 'Seleziona etichetta'],
        'Choose your packaging preference.' => ['tr' => 'Ambalaj tercihi', 'en' => 'Select packaging', 'it' => 'Seleziona imballaggio'],
        'Ambalaj seçimi' => ['en' => 'Select packaging', 'it' => 'Seleziona imballaggio'],
        'Ambalaj seçimiz' => ['en' => 'Select packaging', 'it' => 'Seleziona imballaggio'],
        'Ambalaj Seçiniz' => ['en' => 'Select packaging', 'it' => 'Seleziona imballaggio'],
        'Choose your certificate.' => ['tr' => 'Sertifika seçiniz', 'en' => 'Select certificate', 'it' => 'Seleziona certificato'],
        'Sertifika Türü' => ['en' => 'Certificate type', 'it' => 'Tipo di certificato'],
        'Sertifika Türü Seçiniz' => ['en' => 'Select certificate type', 'it' => 'Seleziona tipo certificato'],
        'Sertifika Seçiniz' => ['en' => 'Select certificate', 'it' => 'Seleziona certificato'],
        'Sertifika seçiniz' => ['en' => 'Select certificate', 'it' => 'Seleziona certificato'],
        'Select delivery options.' => ['tr' => 'Teslimat seçenekleri', 'en' => 'Select delivery options', 'it' => 'Seleziona opzioni di consegna'],
        'Teslimat Seçenekleri' => ['en' => 'Delivery options', 'it' => 'Opzioni di consegna'],
        'Teslimat seçenekleri' => ['en' => 'Delivery options', 'it' => 'Opzioni di consegna'],
        'Teslimat Seçenkleri' => ['en' => 'Delivery options', 'it' => 'Opzioni di consegna'],
        'Teslimat seçiniz' => ['en' => 'Select delivery', 'it' => 'Seleziona consegna'],
        'Kalıp Seçimi' => ['en' => 'Select fit', 'it' => 'Seleziona vestibilità'],
        'Kalıp Modeli' => ['en' => 'Fit model', 'it' => 'Modello vestibilità'],
        'Kalıp modeli' => ['en' => 'Fit model', 'it' => 'Modello vestibilità'],
        'kalıp modeli' => ['en' => 'Fit model', 'it' => 'Modello vestibilità'],
        'iplik kalitesi seçiniz' => ['en' => 'Select yarn quality', 'it' => 'Seleziona qualità del filo'],
        'İplik seçiniz' => ['en' => 'Select yarn', 'it' => 'Seleziona filo'],
        'Renk varyasyonları' => ['en' => 'Color variations', 'it' => 'Varianti colore'],
        'Beden tabloları' => ['en' => 'Size charts', 'it' => 'Tabelle taglie'],
        'Beden adetleri' => ['en' => 'Size quantities', 'it' => 'Quantità per taglia'],
        'Ürün Özelleştirme' => ['en' => 'Product customization', 'it' => 'Personalizzazione prodotto'],
        'Handels' => ['en' => 'Handles', 'it' => 'Manici'],
        'Bel Çantası' => ['en' => 'Waist bag', 'it' => 'Marsupio'],

        // Options frequently used as matching keys in the dump
        'Nape Binding' => ['tr' => 'Ense biyesi', 'en' => 'Nape binding', 'it' => 'Bies nuca'],
        'Arm Ribbing' => ['tr' => 'Kol ribanası', 'en' => 'Sleeve ribbing', 'it' => 'Costina manica'],
        'Nape of the Moon' => ['tr' => 'Ense ay parçası', 'en' => 'Nape hanger loop', 'it' => 'Asola nuca'],
        'Kol Ribanası' => ['en' => 'Sleeve ribbing', 'it' => 'Costina manica'],
        'kol ribanası' => ['en' => 'Sleeve ribbing', 'it' => 'Costina manica'],
        'Kol Ribanası Çift çizgi' => ['en' => 'Sleeve ribbing (double stripe)', 'it' => 'Costina manica (doppia riga)'],
        'Sleeve Ribbed single line' => ['tr' => 'Kol ribanası tek çizgi', 'en' => 'Sleeve ribbing (single stripe)', 'it' => 'Costina manica (riga singola)'],
        'Ribbed sleeves, double line.' => ['tr' => 'Kol ribanası çift çizgi', 'en' => 'Sleeve ribbing (double stripe)', 'it' => 'Costina manica (doppia riga)'],
        'Ribana Yaka' => ['en' => 'Rib collar', 'it' => 'Collo a costina'],
        'Gömlek Yaka' => ['en' => 'Shirt collar', 'it' => 'Collo camicia'],
        'V Yaka' => ['en' => 'V-neck', 'it' => 'Scollo a V'],
        'O Yaka' => ['en' => 'Crew neck', 'it' => 'Girocollo'],
        'Crew Neck' => ['tr' => 'O yaka', 'en' => 'Crew neck', 'it' => 'Girocollo'],
        'Hoodie ,Kangroo' => ['en' => 'Hoodie, kangaroo pocket', 'it' => 'Felpa con cappuccio e tasca canguro'],
        'Tam Fermuarlı Hoodie' => ['en' => 'Full-zip hoodie', 'it' => 'Felpa full zip'],
        'Yarım Fermuarlı Hoodie' => ['en' => 'Half-zip hoodie', 'it' => 'Felpa half zip'],
        'O-neck sweatshirt' => ['tr' => 'O yaka sweatshirt', 'en' => 'Crew-neck sweatshirt', 'it' => 'Felpa girocollo'],
        'Tam fermuarlı sweat' => ['en' => 'Full-zip sweatshirt', 'it' => 'Felpa full zip'],
        'Yarım Fermuarlı Sweat' => ['en' => 'Half-zip sweatshirt', 'it' => 'Felpa half zip'],
        "I don't want" => ['tr' => 'İstemiyorum', 'en' => "I don't want it", 'it' => 'Non lo desidero'],
        'İstemiyorum' => ['en' => "I don't want it", 'it' => 'Non lo desidero'],
        'istemiyorum' => ['en' => "I don't want it", 'it' => 'Non lo desidero'],
        'İSTEMİYORUM' => ['en' => "I don't want it", 'it' => 'Non lo desidero'],
        'Male/Unisex' => ['tr' => 'Erkek/Unisex', 'en' => 'Men/Unisex', 'it' => 'Uomo/Unisex'],
        'Man /Unisex' => ['tr' => 'Erkek/Unisex', 'en' => 'Men/Unisex', 'it' => 'Uomo/Unisex'],
        'Female' => ['tr' => 'Kadın', 'en' => 'Women', 'it' => 'Donna'],
        'woman' => ['tr' => 'Kadın', 'en' => 'Women', 'it' => 'Donna'],
        'Child' => ['tr' => 'Çocuk', 'en' => 'Kids', 'it' => 'Bambini'],
        'Bebek' => ['en' => 'Baby', 'it' => 'Bebè'],
        'man-SLIM' => ['en' => 'Men slim', 'it' => 'Uomo slim'],
        'man REGULAR' => ['en' => 'Men regular', 'it' => 'Uomo regular'],
        'man OVERSIZE' => ['en' => 'Men oversize', 'it' => 'Uomo oversize'],
        'women REGULAR' => ['en' => 'Women regular', 'it' => 'Donna regular'],
        'women SLIM' => ['en' => 'Women slim', 'it' => 'Donna slim'],
        'women OVERSIZE' => ['en' => 'Women oversize', 'it' => 'Donna oversize'],
        'kids REGULAR' => ['en' => 'Kids regular', 'it' => 'Bambini regular'],
        'Kapuşon içi astar' => ['en' => 'Hood lining', 'it' => 'Fodera cappuccio'],
        'Kordon ve uçlama' => ['en' => 'Drawcord and aglets', 'it' => 'Coulisse e puntali'],
        'Kuşgözü' => ['en' => 'Eyelet', 'it' => 'Occhiello'],
        'Kuş gözü' => ['en' => 'Eyelet', 'it' => 'Occhiello'],
        'Fleto Cep' => ['en' => 'Welt pocket', 'it' => 'Taschino con pattina'],
        'Reglan Kol' => ['en' => 'Raglan sleeve', 'it' => 'Manica raglan'],
        'Pocket' => ['tr' => 'Cep', 'en' => 'Pocket', 'it' => 'Tasca'],
        'Cep' => ['en' => 'Pocket', 'it' => 'Tasca'],
        'Arka cep' => ['en' => 'Back pocket', 'it' => 'Tasca posteriore'],
        'kanguru cep' => ['en' => 'Kangaroo pocket', 'it' => 'Tasca canguro'],
        'Yaka tek çizgi' => ['en' => 'Collar single stripe', 'it' => 'Collo riga singola'],
        'Yaka çift çizgi' => ['en' => 'Collar double stripe', 'it' => 'Collo doppia riga'],
        'Double Ribbed Collar' => ['tr' => 'Yaka çift çizgi', 'en' => 'Double ribbed collar', 'it' => 'Collo a costina doppia riga'],
        'Ribbed Collar (Single Line)' => ['tr' => 'Yaka tek çizgi', 'en' => 'Ribbed collar (single stripe)', 'it' => 'Collo a costina (riga singola)'],
        'Yırtmaç' => ['en' => 'Side slit', 'it' => 'Spacco laterale'],
        'Ense Biye' => ['en' => 'Nape binding', 'it' => 'Bies nuca'],
        'sağ yanda kalem cebi' => ['en' => 'Right-side pen pocket', 'it' => 'Tasca penna laterale destra'],
        'İç Cüzdan cebi' => ['en' => 'Inner wallet pocket', 'it' => 'Tasca interna porta documenti'],
        'Alt cep Sağ yanda kalem cebi' => ['en' => 'Lower pocket with right-side pen pocket', 'it' => 'Tasca inferiore con tasca penna a destra'],
        'Üst cep (18x23 )' => ['en' => 'Upper pocket (18x23)', 'it' => 'Tasca superiore (18x23)'],
        'zarf dikiş' => ['en' => 'Envelope stitch', 'it' => 'Cucitura a busta'],
        'Zarf Dikişi' => ['en' => 'Envelope stitch', 'it' => 'Cucitura a busta'],
        'Üstten Mıknatıslı kapama' => ['en' => 'Magnetic top closure', 'it' => 'Chiusura superiore magnetica'],
        'Üstten Mıknatıslı Kapama' => ['en' => 'Magnetic top closure', 'it' => 'Chiusura superiore magnetica'],
        'Üstten Fermuarlı kapama' => ['en' => 'Zipped top closure', 'it' => 'Chiusura superiore con zip'],
        'istediğiniz renk (pantone)' => ['en' => 'Custom color (Pantone)', 'it' => 'Colore personalizzato (Pantone)'],
        'Economic' => ['tr' => 'Ekonomik', 'en' => 'Economy', 'it' => 'Economico'],
        'Preminium' => ['tr' => 'Premium', 'en' => 'Premium', 'it' => 'Premium'],
        'Premium' => ['en' => 'Premium', 'it' => 'Premium'],
        'Uçak' => ['en' => 'Air freight', 'it' => 'Via aerea'],
        'transportation by road' => ['tr' => 'Karayolu', 'en' => 'Road freight', 'it' => 'Via terra'],
        'Ziplock Bag' => ['tr' => 'Kilitli torba', 'en' => 'Zip bag', 'it' => 'Busta zip'],
        'Standard Printed PP Bag' => ['tr' => 'Standart baskılı PP torba', 'en' => 'Standard printed PP bag', 'it' => 'Busta PP stampata standard'],
        '200 needles' => ['tr' => '200 iğne', 'en' => '200 needles', 'it' => '200 aghi'],

        // Categories / products from the new dump
        'T-shirt' => ['en' => 'T-shirt', 'it' => 'T-shirt'],
        'Shirts' => ['en' => 'Shirts', 'it' => 'Camicie'],
        'Workwear' => ['en' => 'Workwear', 'it' => 'Abbigliamento da lavoro'],
        'Tote bags' => ['en' => 'Tote bags', 'it' => 'Borse shopper'],
        'Knitted Products' => ['en' => 'Knitted products', 'it' => 'Articoli in maglia'],
        'Fleece Products' => ['en' => 'Fleece products', 'it' => 'Articoli in pile'],
        'Accessory' => ['en' => 'Accessories', 'it' => 'Accessori'],
        'Pants' => ['en' => 'Pants', 'it' => 'Pantaloni'],
        'Makyaj çantaları' => ['en' => 'Makeup bags', 'it' => 'Pochette make-up'],
        'Basic T-shirt' => ['en' => 'Basic T-shirt', 'it' => 'T-shirt basic'],
        'Clasic Shirt' => ['en' => 'Classic shirt', 'it' => 'Camicia classica'],
        'Clasic (socket)' => ['en' => 'Classic socks', 'it' => 'Calzini classici'],
        'Waist Apron' => ['en' => 'Waist apron', 'it' => 'Grembiule da vita'],
        'Fanny pack' => ['en' => 'Fanny pack', 'it' => 'Marsupio'],
        'Hawaiian shirt' => ['en' => 'Hawaiian shirt', 'it' => 'Camicia hawaiana'],
        'Uniform Shirt' => ['en' => 'Uniform shirt', 'it' => 'Camicia da uniforme'],
        'non-gusseted bag' => ['en' => 'Non-gusseted bag', 'it' => 'Borsa senza soffietto'],
        'Sport socks' => ['en' => 'Sport socks', 'it' => 'Calzini sportivi'],
        'bottom bellows bag' => ['en' => 'Bottom gusset bag', 'it' => 'Borsa con soffietto inferiore'],
        'Three-sided bellows bag' => ['en' => 'Three-sided gusset bag', 'it' => 'Borsa con soffietto a tre lati'],
        'Hip-Hop hats' => ['en' => 'Hip-hop hats', 'it' => 'Cappelli hip-hop'],
        'Christmas sweater' => ['en' => 'Christmas sweater', 'it' => 'Maglione natalizio'],
        'knitted scarf' => ['en' => 'Knitted scarf', 'it' => 'Sciarpa in maglia'],
        'sweatpants' => ['en' => 'Sweatpants', 'it' => 'Pantaloni della tuta'],
        'Jaceket' => ['en' => 'Jacket', 'it' => 'Giacca'],
        'waistcoat' => ['en' => 'Waistcoat', 'it' => 'Gilet'],
        'beanie' => ['en' => 'Beanie', 'it' => 'Berretto'],
        'Bathrobes' => ['en' => 'Bathrobes', 'it' => 'Accappatoi'],
        'Ponchos Adult' => ['en' => 'Adult ponchos', 'it' => 'Poncho adulti'],
        'Poncho Kıds' => ['en' => 'Kids poncho', 'it' => 'Poncho bambini'],
        'Umbrella' => ['en' => 'Umbrella', 'it' => 'Ombrello'],
        'ceramic mug' => ['en' => 'Ceramic mug', 'it' => 'Tazza in ceramica'],
        'Natural-raw-ham' => ['en' => 'Natural / raw / undyed', 'it' => 'Naturale / grezzo'],
        'Cep 16x14 cm' => ['en' => 'Pocket 16x14 cm', 'it' => 'Tasca 16x14 cm'],
        'Cep  16x14 cm' => ['en' => 'Pocket 16x14 cm', 'it' => 'Tasca 16x14 cm'],
        'Cep  16x14cm' => ['en' => 'Pocket 16x14 cm', 'it' => 'Tasca 16x14 cm'],
        'kids  OVERSİZE' => ['en' => 'Kids oversize', 'it' => 'Bambini oversize'],
    ],
];
